### PR TITLE
A bucket of issues fixed

### LINKED ISSUE #3: Provide ability to configure cursor visibility in different modes
When running the browser in different modes such as kiosk or normal windowed view, the end user may want to toggle the cursor visibility. Currently, this is configurable only in `kiosk` mode.

### LINKED ISSUE #10: Rotating screens causes detected resolution issues
Users currently have to use the ROTATE_DISPLAY and WINDOW_SIZE enVars to get a screen rotated and viewed correctly. Look into whether we can swap the values of the detected resolution, to do this for the user when they set the ROTATE variable:

Example:
- detected resolution = 1920,1080
- rotate setting = left
- applied resolution = 1080,1920

### LINKED ISSUE #11: Add default flag value for window-position
The chromium browser shows a black border in the top and left sides of the screen by default. In order to utilize the full real estate of the screen, one has to add an environment variable `FLAGS` with a value of `--window-position=0,0`.

This should be the default value for this flag.

### LINKED ISSUE #13: Add support for Raspberry Pi 3 64-bit variant and Fin

### LINKED ISSUE #14: Document WINDOW_SIZE variable

### LINKED ISSUE #16: We shouldn't overwrite the KIOSK Flag
https://github.com/balenablocks/browser/blob/2739c0f00933116d5e4eff4ee453dbd067702d1f/start.sh#L86

If we overwrite the KIOSK flag, it is not as easy to detect if KIOSK mode is enabled when we use the browser block in other projects.

Also,  It doesn't seem we are using the exported KIOSK values in the flags when launching chromium. 
https://github.com/balenablocks/browser/blob/2739c0f00933116d5e4eff4ee453dbd067702d1f/start.sh#L115

Is https://github.com/balenablocks/browser/blob/2739c0f00933116d5e4eff4ee453dbd067702d1f/start.sh#L88

only necessary?

### LINKED ISSUE #18: Disable GPU by default but allow it to be enabled

### PR DESCRIPTION
**Pull request by phil-d-wilson**
Change-type: patch
Signed-off-by: Phil Wilson <phil@balena.io>

### CODE REVIEW

File: start.sh [hunk 1]
```diff
@@ -66,43 +78,68 @@ fi
...
+    #window size
+    REVERSED_SIZE="$(reverse_window_coordinates $WINDOW_SIZE)"
+    WINDOW_SIZE=$REVERSED_SIZE
+    echo "Reversed window size: $WINDOW_SIZE"
+    
+    #window position, if set
+    if [[ "$WINDOW_POSITION" -ne "0,0" ]]
+    then
+      REVERSED_POSITION="$(reverse_window_coordinates $WINDOW_POSITION)"
+      export WINDOW_POSITION=$REVERSED_POSITION
```
Comment (rahul-thakoor) [inline start.sh:115]: Not sure if overwriting the WINDOW_POSITION variable could cause issues if someone is writing logic to detect it when using block. We encountered this when overwriting KIOSK value

File: start.sh [hunk 2]
```diff
@@ -66,43 +78,68 @@ fi
...
-        export CURSOR='-- -nocursor'
-        echo "Disabling cursor"
-    fi
+    export CHROME_LAUNCH_URL="--app=$LAUNCH_URL" 
   else
-    export KIOSK=''
     export CHROME_LAUNCH_URL="$LAUNCH_URL"
     export CURSOR=''
     echo "Enabling cursor"
 fi
```
Comment (rahul-thakoor) [inline start.sh:131]: Maybe we shouldn't modify cursor if we are not in kiosk mode  since we now allow to modify the cursor visibility independently in this PR

considering a generic use case of browser block and given kiosk mode is not the default, we can show the cursor by default

**Review by rahul-thakoor — CHANGES_REQUESTED** [review]

File: start.sh (hunk 2 above)
Comment (phil-d-wilson) [reply start.sh:131]: Yep - good catch, I missed that line. It might be quicker for you to edit it, since I'm tied up today.

Comment (phil-d-wilson) [reply start.sh:131]: @rahul-thakoor ---^

File: start.sh (hunk 1 above)
Comment (rahul-thakoor) [reply start.sh:115]: thoughts here @phil-d-wilson ?

File: start.sh (hunk 2 above)
Comment (rahul-thakoor) [reply start.sh:131]: ok. I will do that
